apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: gitea-mysql
  namespace: gitea
spec:
  selector:
    matchLabels:
      app: gitea-mysql
  serviceName: gitea-mysql
  template:
    metadata:
      labels:
        app: gitea-mysql
    spec:
      containers:
      - image: mysql/mysql-server:latest
        imagePullPolicy: IfNotPresent
        name: gitea-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpass
              key: password
        ports:
        - containerPort: 3306
          name: gitea-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-mysql-pvc