apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "gitea"
  name: "gitea"
spec:
  storageClassName: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi" 