apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-mysql-pvc
  namespace: gitea
spec:
  storageClassName: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi