apiVersion: v1
kind: Service
metadata:
  name: gitea-web
  namespace: gitea
  labels: 
    app: gitea
spec:
  selector:
    app: gitea
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  ports:
  - port: 22
    targetPort: 22
    name: gitea-ssh
  selector:
    app: gitea
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-mysql
  namespace: gitea
spec:
  ports:
  - port: 3306
  selector:
    app: gitea-mysql
  clusterIP: None